// Code generated by Arduino IoT Cloud, DO NOT EDIT.

#include <ArduinoIoTCloud.h>
#include <Arduino_ConnectionHandler.h>

const char SSID[]     = SECRET_SSID;    // Network SSID (name)
const char PASS[]     = SECRET_OPTIONAL_PASS;    // Network password (use for WPA, or use as key for WEP)

void onGasLevelChange();
void onHumidityLevelChange();
void onTempLevelChange();

float gasLevel;
float humidityLevel;
float tempLevel;

void initProperties(){

  ArduinoCloud.addProperty(gasLevel, READWRITE, ON_CHANGE, onGasLevelChange);
  ArduinoCloud.addProperty(humidityLevel, READWRITE, ON_CHANGE, onHumidityLevelChange);
  ArduinoCloud.addProperty(tempLevel, READWRITE, ON_CHANGE, onTempLevelChange);



}

WiFiConnectionHandler ArduinoIoTPreferredConnection(SSID, PASS);
